[project]
name = "omniinspect"
version = "0.1.0"
description = "OmniInspect Flask App"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "Flask>=3.0.0",
    "Werkzeug>=3.0.0",
    "Pillow>=10.0.0",
    "reportlab>=4.0.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0"
]

[tool.vercel]
entrypoint = "app.py:app"
